# Generated by Django 6.0.1 on 2026-01-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
        migrations.AddField(
            model_name="song",
            name="chords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
