# Generated by Django 6.0.1 on 2026-01-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_song_audio_file_song_chords"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="analyzed",
            field=models.BooleanField(default=False),
        ),
    ]
