# Generated by Django 6.0.1 on 2026-05-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_song_analyzed"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="tabs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
